# -*- coding: utf-8 -*-
"""stream_jantung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFuJXbeh8GIWJSOOVYo39Xx3vXOySJI9
"""

import pickle
import numpy as np
import streamlit as st

#load modelnya
model = pickle.load(open('penyakit_jantung_koroner.sav','rb'))

#judul web
st.title('Prediksi Penyakit Jantung Koroner')

col1, col2, col3 = st.columns(3)

with col1 :
  age = st.number_input('Masukkan Umur')
with col2 :
  gender = st.number_input('masukkan jenis kelamin')
with col3 :
  chestpain = st.number_input('masukkan jenis nyeri dada')
with col1 :
  restingBP = st.number_input('masukkan tekanan darah')
with col2 :
  chol = st.number_input('masukkan nilai kolestrol')
with col3 :
  fasting_blood_sugar = st.number_input('masukkan gula darah')
with col1 :
  resting_electro = st.number_input('masukkan nilai elektrokardiografi')
with col2 :
  max_heart_rate = st.number_input('masukkan nilai frekuensi jantung')
with col3 :
  exerciseangia = st.number_input('masukkan induksi angina')
with col1 :
  oldpeak = st.number_input('masukkan nilai oldpeak')
with col2 :
  slope = st.number_input('masukkan nilai slope')
with col3 :
  noofvessels = st.number_input('masukkan nilai vessels')

heart_diagnosis = ''

#membuat tombol prediksi
if st.button('prediksi penyakit jantung koroner') :
  heart_prediction = model.predict([[age, gender, chestpain, restingBP, chol, fasting_blood_sugar, resting_electro, max_heart_rate, exerciseangia, oldpeak, slope, noofvessels]])
  if (heart_prediction[0]==1):
    heart_diagnosis = 'pasien terkena penyakit jantung koroner'
  else :
    heart_diagnosis = 'pasien tidak terkena penyakit jantung koroner'

st.success(heart_diagnosis)